'use strict';
const G=SimGame,app=document.querySelector('#app');let game=null,current=0,revealed=false,resetConfirm=false;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,cls='',disabled=false)=>`<button class="${cls}" data-action="${action}" ${disabled?'disabled':''}>${label}</button>`;
const title={reveal:'秘密發牌',event:'資安事件',discussion:'團隊討論',night:'夜晚行動',vote:'推理投票',ending:'真相揭曉'};
function announce(t){document.querySelector('#status').textContent=t;}
function roster(){return game.players.map(p=>`<button class="person ${p.id===current?'selected':''} ${p.alive?'':'out'}" data-player="${p.id}" aria-pressed="${p.id===current}"><span class="avatar" aria-hidden="true">${p.code}</span><span>${p.name}<small>${p.alive?'參與中':'已淘汰'}</small></span></button>`).join('');}
function options(items,selected,action){return `<div class="options">${items.map((x,i)=>`<button class="${selected===i?'selected':''}" data-action="${action}" data-value="${i}" aria-pressed="${selected===i}">${String.fromCharCode(65+i)}. ${esc(x)}</button>`).join('')}</div>`;}
function targets(p){return G.alive(game).filter(t=>p.role==='駭客'?t.role!=='駭客':p.role==='網路警察'?t.id!==p.id:p.role==='政府人員'?t.id!==game.lastProtected:false);}
function privatePanel(p){
 if(!revealed)return `<div class="cover"><div class="avatar" style="margin:0 auto">${p.code}</div><h3>請把裝置交給 ${p.name}</h3><p class="muted">確認只有這位玩家查看後，再打開私人畫面。<br>切換玩家會自動收起，已提交的操作仍會保留。</p>${button('我是'+p.name+'，查看','reveal','primary')}</div>`;
 const skill={'駭客':'夜晚與隊友共同選擇一名非駭客目標。選擇不一致或未提交會讓攻擊失敗。','政府人員':'每夜保護一人，可保護自己，但不能連續兩夜保護同一人。','網路警察':'每夜查驗一名其他存活玩家，只看見是否為駭客。','民眾':'沒有夜晚技能。觀察發言與票向，白天參與討論與投票。'}[p.role];
 let html=`<div class="secret"><span class="eyebrow">只給 ${p.name} 的私人資訊</span><h3>${p.role} · ${p.role==='駭客'?'駭客陣營':'守護陣營'}</h3><p>${skill}</p><p class="muted">人物小祕密：${p.background}</p>${p.role==='駭客'?`<p>駭客隊友：${game.players.filter(t=>t.role==='駭客'&&t.id!==p.id).map(t=>t.name).join('、')}</p>`:''}${(game.checks[p.id]||[]).map(c=>`<p>第 ${c.day} 夜查驗：${game.players[c.target].name} → ${c.hacker?'駭客':'非駭客'}</p>`).join('')}${button('收起私人畫面','hide')}</div>`;
 if(!p.alive)html+='<p class="badge">已淘汰：可以作答，但不能發言、選防護措施、投票或使用技能。</p>';
 if(game.phase==='event'){const e=G.events[game.event];html+=`<h3>我的處理方式</h3>${options(e.options,game.answers[p.id],'answer')}<p class="muted">${game.answers[p.id]===undefined?'尚未選擇；可先切換其他玩家。':'已保存，可在結算前修改。答案不會公開指名。'}</p>`;}
 if(game.phase==='discussion'){
  const e=G.events[game.event],a=game.answers[p.id];html+=`<h3>我的事件回饋</h3><p>${a===undefined?'這次未作答。':a===e.safe?'你的安全判斷成立。':'這個選擇仍有風險，看看下面的提醒。'}</p><p>${e.why}</p>`;
  if(p.alive)html+=`<h3>投票選擇團隊防護措施</h3>${options(e.measures,game.measures[p.id],'measure')}<p class="muted">這不是停權投票，不影響夜晚攻擊；個人選擇不公開指名。</p><form id="messageForm"><label for="message">以 ${p.name} 發言</label><textarea id="message" maxlength="300" required placeholder="例如：這份文件不應有指揮工具的權限。"></textarea><button class="primary">送出發言</button></form>`;
 }
 if(game.phase==='night'&&p.alive){if(p.role==='民眾')html+='<h3>夜晚等待中</h3><p>你沒有夜晚技能。切換其他玩家，或等測試者結算。</p>';else{const ts=targets(p);html+=`<h3>${p.role==='駭客'?'攻擊':p.role==='政府人員'?'保護':'查驗'}目標</h3><form id="nightForm"><label for="target">選擇存活玩家</label><select id="target" required><option value="">請選擇</option>${ts.map(t=>`<option value="${t.id}" ${game.night[p.id]===t.id?'selected':''}>${t.name}${t.id===p.id?'（自己）':''}</option>`).join('')}</select><button class="primary">保存夜晚行動</button></form><p class="muted">${game.night[p.id]!==undefined?'行動已保存；可修改。':'尚未提交。'}</p>`;if(p.role==='駭客'){html+=`<label for="attackEvent">下一日攻擊情境（兩名駭客共用，最後設定為準）</label><select id="attackEvent"><option value="">由系統選取</option>${G.events.map((e,i)=>!game.used.includes(i)?`<option value="${i}" ${game.nextEvent===i?'selected':''}>${e.title}</option>`:'').join('')}</select><p class="muted">此處沒有真正執行攻擊或外部連結。</p>`;}}}
 if(game.phase==='vote'&&p.alive)html+=`<h3>${game.runoff?'平票決選':'我的停權投票'}</h3><form id="voteForm"><label for="voteTarget">投給一名其他存活玩家或棄票</label><select id="voteTarget"><option value="-1">棄票</option>${G.alive(game).filter(t=>t.id!==p.id&&(!game.runoff||game.runoff.includes(t.id))).map(t=>`<option value="${t.id}" ${game.votes[p.id]===t.id?'selected':''}>${t.name}</option>`).join('')}</select><button class="primary">保存投票</button></form><p class="muted">${game.votes[p.id]===undefined?'尚未提交；結算時視為棄票。':'票已保存，結算前可修改。'}</p>`;
 return html;
}
function ending(){const finished=game.winner!=='中止'&&game.winner!=='未分勝負';return `<section class="card"><span class="eyebrow">CASE CLOSED</span><h1>${finished?game.winner+'獲勝':game.winner}</h1><p>${game.winner==='守護陣營'?'全部駭客已停權。':game.winner==='駭客陣營'?'存活駭客人數已達其他存活玩家人數。':'本局不宣布陣營勝負。'}</p><div class="players">${game.players.map(p=>`<div class="person"><span class="avatar">${p.code}</span><strong>${p.name}</strong><small>${p.role} · ${p.alive?'存活':'已淘汰'}</small></div>`).join('')}</div><h3>團隊防線</h3><p>形成合理防護措施 ${game.defenses.filter(d=>d.safe).length}／${game.defenses.length} 次。這是遊戲紀錄，不是安全認證。</p>${button('重新發牌，開始新局','new','primary')}</section><section class="card"><h2>個人學習回顧</h2><label for="reviewPlayer">查看玩家</label><select id="reviewPlayer">${game.players.map(p=>`<option value="${p.id}" ${p.id===current?'selected':''}>${p.name}</option>`).join('')}</select>${game.history.map(h=>{const e=G.events[h.event],a=h.answers[current];return `<div class="record"><strong>第 ${h.day} 日：${e.title}</strong><p>${a===undefined?'未作答':a===e.safe?'安全判斷成立':'待練習'}${a===undefined?'':' · '+esc(e.options[a])}</p><p class="muted">${e.why}</p></div>`;}).join('')||'<p>尚未完成事件。</p>'}</section><section class="card"><h2>真相與操作紀錄</h2>${game.logs.map(l=>`<div class="record">${esc(l)}</div>`).join('')}${(game.nightHistory||[]).map(n=>`<div class="record">第 ${n.day} 夜技能：${Object.entries(n.actions).map(([id,t])=>`${game.players[id].name}（${game.players[id].role}）→${game.players[t].name}`).join('、')||'無提交'}</div>`).join('')}</section>`;}
function render(){
 if(!game){app.innerHTML=`<div class="hero"><section><span class="eyebrow">PLAYTEST · 01</span><h1>熟悉的隊友，<br>陌生的秘密。</h1><p>七人之中有兩名駭客。白天推理，夜晚行動；<br>一起辨識 AI 工具背後的風險。</p><div class="actions">${button('建立模擬房間','new','primary')}</div><p class="muted">不用登入、不用等待其他裝置。這不是房號連線版。</p></section><section class="notebook"><h2>這次可以測什麼？</h2><p>01 · 七張人物卡與隨機秘密陣營</p><p>02 · 攻擊、保護、查驗</p><p>03 · 資安事件與文字討論</p><p>04 · 防護決策、停權投票與結局</p></section></div><section class="card" style="margin-top:35px"><h2>一台裝置怎麼試玩？</h2><p>選擇玩家 → 打開私人畫面 → 保存操作 → 收起並切換玩家 → 使用「測試者控制」結算。</p><p>第一日不淘汰；之後白天投票。駭客人數達守護者人數就獲勝，全部駭客停權則守護陣營勝。</p><p class="muted">這版沒有倒數、真正房間、即時連線或重連。刷新會清除；測試者能查看所有角色，不適合公平正式對戰。</p></section>`;return;}
 if(game.phase==='ending'){app.innerHTML=ending();return;}
 const p=game.players[current],e=G.events[game.event];let publicContent='';
 if(game.phase==='reveal')publicContent='<p>先依序切換七名玩家查看角色。第一日不淘汰；民眾答錯題也不代表是駭客。</p>';
 if(['event','discussion'].includes(game.phase)){publicContent+=`<span class="chip">${e.topic}</span><h3>${e.title}</h3><blockquote>${esc(e.text)}</blockquote>`;if(game.phase==='discussion'){const counts=[0,0,0];G.alive(game).forEach(t=>{const a=game.answers[t.id];if(a!==undefined)counts[a]++;});publicContent+=`<h3>存活玩家匿名作答分布</h3><div class="counts">${counts.map((n,i)=>`<span class="chip">${String.fromCharCode(65+i)}：${n} 人</span>`).join('')}<span class="chip">未答：${G.alive(game).length-counts.reduce((a,b)=>a+b,0)} 人</span></div><p class="muted">不能從答題判定陣營。先討論如何處理，再討論可疑發言。</p>`;}}
 if(game.phase==='night')publicContent='<p>存活玩家私下使用技能。駭客需選相同目標；未提交不執行。政府人員不能連續保護同一人。</p>';
 if(game.phase==='vote')publicContent=`<p>${game.runoff?'決選名單：'+game.runoff.map(id=>game.players[id].name).join('、'):'各自投票，結算後才公布票向。'}最高票須高於棄票數才能停權；首次候選人平票進入決選，再平票則無人停權。</p>`;
 const totals=game.phase==='event'?`${Object.keys(game.answers).length}／7 人已作答`:game.phase==='vote'?`${Object.keys(game.votes).length}／${G.alive(game).length} 人已投票`:game.phase==='discussion'?`${Object.keys(game.measures).length}／${G.alive(game).length} 人已選防護措施`:'夜晚提交細節不公開';
 const next={reveal:'開始第一日事件',event:'結束作答，進入討論',discussion:game.day===1?'結算防護，進入第一夜':'結算防護，開始停權投票',night:'結算夜晚，進入白天',vote:game.runoff?'結算決選':'結算停權投票'}[game.phase];
 app.innerHTML=`<div class="phase"><div><span class="eyebrow">DAY ${String(game.day).padStart(2,'0')}</span><h2>${title[game.phase]}${game.runoff?' · 決選':''}</h2></div><span class="tag">${G.alive(game).length} 人存活</span></div><div class="layout"><aside><section class="card"><h3>切換玩家</h3><div class="roster">${roster()}</div><p class="muted">只代表切換本機視角，不是其他裝置登入。</p></section><details class="card"><summary>公開人物資料</summary><h3>${p.name} · ${p.job}</h3><p>${p.relation}</p><p class="muted">人物背景與秘密陣營無關。</p></details></aside><div><section class="card">${publicContent}</section><section class="card">${privatePanel(p)}</section>${game.phase==='discussion'?`<section class="card"><h3>本日聊天室</h3><div class="messages">${game.messages.filter(m=>m.day===game.day).map(m=>`<div class="record"><strong>${game.players[m.id].name}</strong>：${esc(m.text)}</div>`).join('')||'<p class="muted">還沒有發言。也可現場討論。</p>'}</div></section>`:''}<section class="card host"><span class="eyebrow">測試者控制 · 非正式對戰功能</span><p>${totals}</p><p class="muted">手動結算不會等待所有人；漏答保留為未作答、漏投視為棄票、漏技能不執行。</p><div class="actions">${button(next,'advance','primary')}${button('中止本局','abort')}${button(resetConfirm?'確認重新發牌':'重新開始','reset')}</div>${resetConfirm?'<p class="badge">再次按下將清除本局並重新發牌。</p>':''}</section><details class="card"><summary>公開事件紀錄</summary>${game.logs.map(l=>`<div class="record">${esc(l)}</div>`).join('')||'<p>尚無紀錄。</p>'}</details></div></div>`;
}
app.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;try{if(b.dataset.player!==undefined){current=Number(b.dataset.player);revealed=false;resetConfirm=false;announce('已切換玩家，私人資訊已遮住。');render();return;}const a=b.dataset.action;if(a==='new'){game=G.create();current=0;revealed=false;}else if(a==='reveal')revealed=true;else if(a==='hide')revealed=false;else if(a==='answer')G.answer(game,current,Number(b.dataset.value));else if(a==='measure')G.measure(game,current,Number(b.dataset.value));else if(a==='advance'){G.advance(game);revealed=false;resetConfirm=false;announce('已結算，進入'+title[game.phase]+'。');}else if(a==='abort'){game.winner='中止';game.phase='ending';}else if(a==='reset'){if(resetConfirm){game=G.create();current=0;revealed=false;resetConfirm=false;}else resetConfirm=true;}render();}catch(e){announce(e.message);}});
app.addEventListener('submit',ev=>{ev.preventDefault();try{if(ev.target.id==='nightForm'){G.act(game,current,Number(document.querySelector('#target').value));announce('夜晚行動已保存。');}else if(ev.target.id==='voteForm'){G.vote(game,current,Number(document.querySelector('#voteTarget').value));announce('投票已保存。');}else if(ev.target.id==='messageForm'){if(game.phase!=='discussion'||!game.players[current].alive)throw Error('目前不能發言。');const text=document.querySelector('#message').value.trim();if(!text)throw Error('請輸入內容。');game.messages.push({day:game.day,id:current,text:text.slice(0,300)});announce('發言已送出。');}render();}catch(e){announce(e.message);}});
app.addEventListener('change',ev=>{if(ev.target.id==='attackEvent')game.nextEvent=ev.target.value===''?undefined:Number(ev.target.value);if(ev.target.id==='reviewPlayer'){current=Number(ev.target.value);render();}});
render();
